export const GET = "GET";
export const POST = "POST";
export const PUT = "PUT";
export const DELETE = "DELETE";

export const GET_USER = "GET_USER";
export const ADD_USER = "ADD_USER";
export const USER_ERROR = "USER_ERROR";

export const NEW_PEDIGREE = "NEW_PEDIGREE";
export const UPDATE_NEW_PEDIGREE = "UPDATE_NEW_PEDIGREE";

export const GET_PEDIGREE = "GET_PEDIGREE";
export const UPDATE_PEDIGREE = "UPDATE_PEDIGREE";
export const PEDIGREE_ERROR = "PEDIGREE_ERROR";

export const FAMILY_LOADING = "FAMILY_LOADING";
export const GET_FAMILY = "GET_FAMILY";
export const CLEAR_FAMILY = "CLEAR_FAMILY";
export const UPDATE_FAMILY = "UPDATE_FAMILY";
export const FAMILY_ERROR = "FAMILY_ERROR";
export const RENDER_STEPPER = "RENDER_STEPPER";
export const RENDER_TREE = "RENDER_TREE";
export const SET_NEW_FAMILY_PAYLOAD = "SET_NEW_FAMILY_PAYLOAD";
export const GET_EDITED_FAMILY = "GET_EDITED_FAMILY";

export const ADD_PARENT = "ADD_PARENT";
export const ADD_SIBLING = "ADD_SIBLING";

export const SAVE_PARENT = "SAVE_PARENT";
export const SAVE_SIBLING = "SAVE_SIBLING";
export const ADD_SPOUSE = "ADD_SPOUSE";
export const SAVE_SPOUSE = "SAVE_SPOUSE";
export const SAVE_ERROR = "SAVE_ERROR";

export const ADD_CHILD = "ADD_CHILD";
export const SAVE_CHILD = "SAVE_CHILD";

export const ADD_FAMILY = "ADD_FAMILY";
export const CANCEL_MODAL = "CANCEL_MODAL";

export const SAVE_PARENTS = "SAVE_PARENTS";

export const GET_EDIT_PERSON = "GET_EDIT_PERSON";
export const ADD_TREE = "ADD_TREE";
export const TREE_ERROR = "TREE_ERROR";

export const ADD_PARENT_VIA_PLACEHOLDER = "ADD_PARENT_VIA_PLACEHOLDER";
export const SAVE_PARENT_VIA_PLACEHOLDER= "SAVE_PARENT_VIA_PLACEHOLDER";
export const SELECT_USER = "SELECT_USER";
export const GET_TREES = "GET_TREES";
export const TREES_LOADING="TREES_LOADING"
export const TREE_PERSON_SEARCH_OPTIONS = "TREE_PERSON_SEARCH_OPTIONS";

export const PERSON_PAGE_LOADING = "PERSON_PAGE_LOADING";
export const REFETCHED = "REFETCHED";
export const WHOLE_REFETCHED = "WHOLE_REFETCHED";
export const PARTIAL_REFETCHED = "PARTIAL_REFETCHED";
export const FETCH_PARENTS = "FETCH_PARENTS";
export const UPDATE_PARENTS = "UPDATE_PARENTS";
export const FETCH_SPOUSES = "FETCH_SPOUSES";
export const UPDATE_SPOUSES = "UPDATE_SPOUSES";
export const PERSON_LOADING = "PERSON_LOADING";
export const GET_PERSON = "GET_PERSON";

export const GET_PERSONAL_INFO = "GET_PERSONAL_INFO";
export const GET_EVENTS = "GET_EVENTS";
export const GET_SPOUSES = "GET_SPOUSES";
export const GET_PARENTS = "GET_PARENTS";
export const GET_LIFEEVENTS = "GET_LIFEEVENTS";
export const ADD_LIFEEVENT = "ADD_LIFEEVENT";
export const SUCCESS_LIFEEVENT ="SUCCESS_LIFEEVENT";
export const FAIL_LIFEEVENT ="FAIL_LIFEEVENT";

export const UPDATE_PERSON="UPDATE_PERSON";
export const UPDATE_PERSONAL_INFO = "UPDATE_PERSONAL_INFO";
export const UPDATE_PERSONINFO_ONLY = "UPDATE_PERSONINFO_ONLY";
export const UPDATE_SPOUSES_AND_CHILDREN = "UPDATE_SPOUSES_AND_CHILDREN";
export const UPDATE_PARENTS_AND_SIBLINGS = "UPDATE_PARENTS_AND_SIBLINGS";
export const UPDATE_EVENTS = "UPDATE_EVENTS";
export const UPDATE_LIFE_EVENTS = "UPDATE_LIFE_EVENTS";
export const PERSON_ERROR = "PERSON_ERROR";

export const IMPORT_GEDCOM = "IMPORT_GEDCOM";
export const PROGRESS_BAR = "PROGRESS_BAR";
export const GEDCOM_ERROR = "GEDCOM_ERROR";
export const UPDATED_GEDCOM = "UPDATED_GEDCOM";

export const GET_IMPORT_STATUS = "GET_IMPORT_STATUS";
export const IMPORT_STATUS_ERROR = "IMPORT_STATUS_ERROR";

export const ASSIGN_HOMEPERSON = "ASSIGN_HOMEPERSON";
export const ASSIGN_ERROR = "ASSIGN_ERROR";

export const SELECT_HOMEPERSON = "SELECT_HOMEPERSON";
export const SELECT_HOMEPERSON_ERROR = "SELECT_HOMEPERSON_ERROR";

export const AUTOCOMPLETE_REQUEST = "AUTOCOMPLETE_REQUEST";
export const AUTOCOMPLETE_TEST = "AUTOCOMPLETE_TEST";
export const AUTOCOMPLETE_ERROR = "AUTOCOMPLETE_ERROR";

export const AUTOCOMPLETE_PAGINATION_REQUEST = "AUTOCOMPLETE_PAGINATION_REQUEST";
export const AUTOCOMPLETE_PAGINATION_TEST = "AUTOCOMPLETE_PAGINATION_TEST";
export const AUTOCOMPLETE_PAGINATION_ERROR = "AUTOCOMPLETE_PAGINATION_ERROR";

export const AUTOCOMPLETE_BIRTH_TEST = "AUTOCOMPLETE_BIRTH_TEST";
export const AUTOCOMPLETE_BIRTH_PAGINATION_TEST = "AUTOCOMPLETE_BIRTH_PAGINATION_TEST";
export const CLEAR_BIRTH_OPTIONS="CLEAR_BIRTH_OPTIONS";

export const AUTOCOMPLETE_DEATH_TEST="AUTOCOMPLETE_DEATH_TEST";
export const AUTOCOMPLETE_DEATH_PAGINATION_TEST="AUTOCOMPLETE_DEATH_PAGINATION_TEST";
export const CLEAR_DEATH_OPTIONS="CLEAR_DEATH_OPTIONS";


export const SAVE_PROFILE_IMAGE= "SAVE_PROFILE_IMAGE";
export const IMAGE_LOADING="IMAGE_LOADING";
export const CLEAR_IMAGE="CLEAR_IMAGE";
export const REFETCH_PERSON_INFO="REFETCH_PERSON_INFO";
export const REFETCH_PERSON_BASIC_INFO = "REFETCH_PERSON_BASIC_INFO";
export const PROFILE_IMAGE_LOADING="PROFILE_IMAGE_LOADING";
export const GET_PROFILE_IMAGE="GET_PROFILE_IMAGE";
export const FETCHING_IMAGE="FETCHING_IMAGE";
export const SHOW_IMAGE="SHOW_IMAGE";

export const SET_MODAL_DATA = "SET_MODAL_DATA";
export const PROFILE_LOADING= "PROFILE_LOADING";
export const SHOW_PROFILE="SHOW_PROFILE";
export const SAVE_PROFILE="SAVE_PROFILE";
export const FETCHING_USER_PROFILE_IMAGE="FETCHING_USER_PROFILE_IMAGE";
export const GET_USER_PROFILE_IMAGE="GET_USER_PROFILE_IMAGE";
export const CLEAR_PROFILE_IMAGE="CLEAR_PROFILE_IMAGE";
export const PROFILE_CHANGED = "PROFILE_CHANGED";
export const SET_PROFILE_IMAGE = "SET_PROFILE_IMAGE";
export const CLEAR_EDIT_IMAGE="CLEAR_EDIT_IMAGE";
export const SHOW_EDIT_IMAGE="SHOW_EDIT_IMAGE";
export const PROFILE_IMAGE_UPLOADED = "PROFILE_IMAGE_UPLOADED";
export const REFETCH_PAGE_AFTER_UPLOAD = "REFETCH_PAGE_AFTER_UPLOAD";
export const CLEAR_REFETCH_INFO = "CLEAR_REFETCH_INFO";
export const ADD_PERSON_THUMBNAIL = "ADD_PERSON_THUMBNAIL";
export const IMAGE_UNLOADING = "IMAGE_UNLOADING";
export const ADD_PROFILE_THUMBNAIL = " ADD_PROFILE_THUMBNAIL";
export const ACCESS_CODE_VALIDATING = "ACCESS_CODE_VALIDATING";
export const ACCESS_CODE_INVALID = "ACCESS_CODE_INVALID";
export const ACCESS_CODE_VALID = "ACCESS_CODE_VALID";
export const CLEAR_ACCESS = "CLEAR_ACCESS";

export const ADD_PERSON_HERO_THUMBNAIL = "ADD_PERSON_HERO_THUMBNAIL";
export const SAVE_HERO_IMAGE = "SAVE_HERO_IMAGE";
export const THUMBNAIL_UPLOAD_COMPLETE = "THUMBNAIL_UPLOAD_COMPLETE";
export const GET_HERO_IMAGE = "GET_HERO_IMAGE";
export const RESET_MEDIA = "RESET_MEDIA"
export const CLEAR_STORY_LIKES_PERSONS = "CLEAR_STORY_LIKES_PERSONS";
export const FEATURED_STORY_ID_REDIRECT = "FEATURED_STORY_ID_REDIRECT"

export const UPDATE_USER = "UPDATE_USER";
export const PROFILE_IMAGE_DELETED = "PROFILE_IMAGE_DELETED";
